# Cloudflare Tunnel (locally-managed, outbound-only).
#
# Exposes selected local services to the public internet through
# Cloudflare's edge WITHOUT opening any inbound port on the LXC: `cloudflared`
# dials out to Cloudflare (HTTPS 443 / QUIC 7844) and Cloudflare routes the
# hostnames you configure in the ingress table back down the same connection.
#
# Security model:
#   * The tunnel itself is a local-management tunnel, wired through the pinned
#     nixpkgs `services.cloudflared` module. The tunnel credentials (a JSON
#     file with AccountTag / TunnelID / TunnelSecret — NOT the `eyJ…` token
#     used by remotely-managed tunnels) come from an agenix secret, never Nix
#     config.
#   * Ingress is EMPTY by default and `default = http_status:404` — nothing is
#     routable to the public internet until a hostname is explicitly added.
#     Adding an ingress line is the (intentional) act of going public, so it
#     is deliberately the only step that exposes a service.
#   * INGRESS TARGETS ARE CREDENTIAL-ENFORCED. Each ingress value is a `name`
#     from the tailnet-exposure registry (`hermesDeploy.exposure.services` in
#     modules/exposure.nix), and the local URL is DERIVED from that exposure's
#     port. The same credentials that had to be wired for the tailnet path are
#     therefore required for the public path too. The build fails if an
#     ingress references an unknown exposure, an uncredentialed one
#     (`credentialsConfigured = false`), or one whose `auth.type = "none"` —
#     the insecure opt-in is scoped to the trusted tailnet and never allowed
#     on the public internet.
#   * cloudflared runs as a dynamic system user; systemd loads the credential
#     into a root-owned, 0400 runtime directory, so the agenix file only needs
#     to be root-readable.
#
# Outbound-only: no firewall rule is required or opened. `services.cloudflared`
# only establishes outbound connections.
#
# Requires the exposure registry module (modules/exposure.nix) to be present.

{
  config,
  lib,
  ...
}:

let
  cfg = config.services.cloudflare-tunnel;

  # The registry is the single source of truth for "which services exist and
  # what they are authenticated with". Build a name → exposure lookup so an
  # ingress rule can only ever target a registered, credentialed service.
  exposures = config.hermesDeploy.exposure.services;
  byName = lib.listToAttrs (map (e: lib.nameValuePair e.name e) exposures);

  ingressTargets = lib.attrValues cfg.ingress;
  unknownTargets = lib.filter (n: !(builtins.hasAttr n byName)) ingressTargets;
  uncredentialedTargets = lib.filter (
    n: builtins.hasAttr n byName && !byName.${n}.auth.credentialsConfigured
  ) ingressTargets;
  insecureTargets = lib.filter (
    n: builtins.hasAttr n byName && byName.${n}.auth.type == "none"
  ) ingressTargets;

  # Derive each public URL from the registered exposure's port. Unknown names
  # fall back to 404 so the eval stays clean and the assertion below (not an
  # opaque "attribute missing" error) is what surfaces.
  derivedIngress = lib.mapAttrs (
    host: name:
    if builtins.hasAttr name byName then
      "http://127.0.0.1:${toString byName.${name}.port}"
    else
      "http_status:404"
  ) cfg.ingress;
in
{
  options.services.cloudflare-tunnel = {
    enable = lib.mkEnableOption "Cloudflare Tunnel (locally-managed, outbound-only)";

    tunnelId = lib.mkOption {
      type = lib.types.str;
      default = "00000000-0000-0000-0000-000000000000";
      description = ''
        UUID of the locally-managed tunnel. Must match the TunnelID inside the
        credentials file. Get it from the Cloudflare dashboard (Networking →
        Tunnels → your tunnel) or `cloudflared tunnel list`.
      '';
    };

    credentialsFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Agenix-decrypted tunnel credentials JSON file:
          { "AccountTag": "…", "TunnelID": "…", "TunnelSecret": "…" }
        Generated by `cloudflared tunnel login` / `cloudflared tunnel create
        <name>`. This is NOT the `eyJ…` token used by remotely-managed
        tunnels.
      '';
    };

    ingress = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = ''
        Public hostname → exposure name, where the name must match a `name`
        declared in `hermesDeploy.exposure.services` (modules/exposure.nix).
        The local URL is derived from that exposure's port, and the exposure's
        credentials must be wired — otherwise the build fails. EMPTY by
        default; add entries only to deliberately publish a service, e.g.
          { "dashboard.0u0.ca" = "hermes-dashboard"; }
      '';
      example = {
        "dashboard.0u0.ca" = "hermes-dashboard";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    services.cloudflared.enable = true;

    services.cloudflared.tunnels.${cfg.tunnelId} = {
      credentialsFile = cfg.credentialsFile;
      ingress = derivedIngress;
      # Catch-all: refuse anything that doesn't match an ingress rule. This is
      # what keeps "wired but not yet exposed" truly not-exposed.
      default = "http_status:404";
    };

    assertions = [
      {
        assertion = unknownTargets == [ ];
        message = ''
          services.cloudflare-tunnel: ingress references exposure(s) not
          declared in hermesDeploy.exposure.services: ${toString unknownTargets}.
          Add each to the exposure registry (with credentials) before exposing
          it through the tunnel.
        '';
      }
      {
        assertion = uncredentialedTargets == [ ];
        message = ''
          services.cloudflare-tunnel: ingress would expose service(s) whose
          credentials are not configured: ${toString uncredentialedTargets}.
          Wire the exposure's credential source (agenix secret / env file) so
          credentialsConfigured = true before publishing it.
        '';
      }
      {
        assertion = insecureTargets == [ ];
        message = ''
          services.cloudflare-tunnel: ingress would expose unauthenticated
          service(s) (auth.type = "none") to the PUBLIC internet:
          ${toString insecureTargets}.
          The insecure opt-in is tailnet-only; public exposure requires real
          credentials (basic / bearer / oauth).
        '';
      }
    ];

    warnings =
      lib.optionals (cfg.credentialsFile == null) [
        "services.cloudflare-tunnel: no credentialsFile set — the tunnel cannot connect until the credentials JSON (AccountTag/TunnelID/TunnelSecret) is supplied via the agenix secret."
      ]
      ++ lib.optionals (cfg.ingress != { }) [
        "services.cloudflare-tunnel: ingress rules are configured — the hostname(s) ${builtins.concatStringsSep ", " (builtins.attrNames cfg.ingress)} will be reachable from the PUBLIC INTERNET through Cloudflare."
      ];
  };
}
